name: Deploy Quartz site to GitHub Pages

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as we
# want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Run this workflow on pushes to master
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    # This job uses a GitHub-hosted runner.
    runs-on: ubuntu-latest

    # Skip builds with "[ci skip]" in the commit
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout Quartz
        uses: actions/checkout@v4
        with:
          repository: itspriddle/quartz
          path: quartz
      - name: Clean Quartz content
        working-directory: quartz
        run: |
          rm -rf content
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: quartz/content
      - name: Clean internal files
        working-directory: quartz/content
        run: |
          rm -f README.md
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install node dependencies
        working-directory: quartz
        run: |
          npm install
      - name: Build Quartz site
        working-directory: quartz
        run: |
          npx quartz build --bundleInfo
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz/public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
